<!-- Top level Directory.Build.props -->
<Project>

    <PropertyGroup>
        <!-- Compile and Build Settings -->
        <LangVersion>12</LangVersion>
        <Features>strict</Features>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisMode>Minimum</AnalysisMode>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='netcoreapp3.1'">
		<NUnitFrameworkVersion>3.14.0</NUnitFrameworkVersion>
		<NUnitLiteVersion>3.14.0</NUnitLiteVersion>
	</PropertyGroup>
	
	<PropertyGroup>
		<!-- Common Package Versions -->
		<NUnitFrameworkVersion Condition="'$(NUnitFrameworkVersion)'==''">4.3.2</NUnitFrameworkVersion>
		<NUnitLiteVersion Condition="'$(NUnitLiteVersion)'==''">4.3.2</NUnitLiteVersion>
	</PropertyGroup>

</Project>
